/** Popular JLPT vocabulary in small teach-then-quiz stages. */

function pack(id, title, subtitle, items, extra = {}) {
  return {
    id,
    title,
    subtitle,
    teach: extra.teach || (items.length > 8 ? 'grid' : 'cards'),
    intro: Boolean(extra.intro),
    mix: Boolean(extra.mix),
    chars: items.map(([char, romaji, meaning]) => ({
      char,
      romaji,
      meaning,
      hint: '',
    })),
  };
}

function mix(id, title) {
  return pack(id, title, 'Everything in this level, shuffled.', [], { teach: 'grid', mix: true });
}

export const VOCAB_SCRIPTS = {
  n5: {
    id: 'n5',
    label: 'N5 words',
    kicker: 'First vocabulary',
    blurb: 'Popular JLPT N5 words: greetings, people, time, food, and everyday verbs.',
    kind: 'vocab',
    group: 'words',
    stages: [
      pack(
        'n5-0',
        'Stage 0 · First words',
        'Six everyday words. See the writing, the sound, and the English meaning, then pick them from A–F.',
        [
          ['私', 'watashi', 'I / me'],
          ['日本', 'nihon', 'Japan'],
          ['人', 'hito', 'person'],
          ['水', 'mizu', 'water'],
          ['食べる', 'taberu', 'to eat'],
          ['行く', 'iku', 'to go'],
        ],
        { intro: true }
      ),
      pack('n5-1', 'Stage 1 · Greetings', 'Hello, thanks, yes, no, please.', [
        ['こんにちは', 'konnichiwa', 'hello'],
        ['おはよう', 'ohayou', 'good morning'],
        ['ありがとう', 'arigatou', 'thank you'],
        ['すみません', 'sumimasen', 'excuse me / sorry'],
        ['はい', 'hai', 'yes'],
        ['いいえ', 'iie', 'no'],
        ['お願いします', 'onegaishimasu', 'please'],
        ['さようなら', 'sayounara', 'goodbye'],
        ['はじめまして', 'hajimemashite', 'nice to meet you'],
        ['ください', 'kudasai', 'please give me'],
      ]),
      pack('n5-2', 'Stage 2 · People', 'Family, friends, school roles.', [
        ['あなた', 'anata', 'you'],
        ['彼', 'kare', 'he'],
        ['彼女', 'kanojo', 'she'],
        ['友達', 'tomodachi', 'friend'],
        ['先生', 'sensei', 'teacher'],
        ['学生', 'gakusei', 'student'],
        ['家族', 'kazoku', 'family'],
        ['母', 'haha', 'mother'],
        ['父', 'chichi', 'father'],
        ['子供', 'kodomo', 'child'],
      ]),
      pack('n5-3', 'Stage 3 · Time', 'Today, tomorrow, hours, every day.', [
        ['今日', 'kyou', 'today'],
        ['明日', 'ashita', 'tomorrow'],
        ['昨日', 'kinou', 'yesterday'],
        ['今', 'ima', 'now'],
        ['時', 'ji / toki', 'hour / time'],
        ['分', 'fun / pun', 'minute'],
        ['週', 'shuu', 'week'],
        ['年', 'nen / toshi', 'year'],
        ['毎日', 'mainichi', 'every day'],
        ['いつ', 'itsu', 'when'],
      ]),
      pack('n5-4', 'Stage 4 · Core verbs', 'Do, exist, come, see, buy.', [
        ['する', 'suru', 'to do'],
        ['ある', 'aru', 'to exist (thing)'],
        ['いる', 'iru', 'to exist (person)'],
        ['来る', 'kuru', 'to come'],
        ['見る', 'miru', 'to see / watch'],
        ['聞く', 'kiku', 'to hear / ask'],
        ['話す', 'hanasu', 'to speak'],
        ['飲む', 'nomu', 'to drink'],
        ['買う', 'kau', 'to buy'],
        ['待つ', 'matsu', 'to wait'],
      ]),
      pack('n5-5', 'Stage 5 · Adjectives', 'Big, small, hot, cheap, good.', [
        ['大きい', 'ookii', 'big'],
        ['小さい', 'chiisai', 'small'],
        ['新しい', 'atarashii', 'new'],
        ['古い', 'furui', 'old'],
        ['高い', 'takai', 'expensive / tall'],
        ['安い', 'yasui', 'cheap'],
        ['いい', 'ii', 'good'],
        ['悪い', 'warui', 'bad'],
        ['暑い', 'atsui', 'hot (weather)'],
        ['寒い', 'samui', 'cold (weather)'],
      ]),
      pack('n5-6', 'Stage 6 · Places', 'School, station, home, shop.', [
        ['学校', 'gakkou', 'school'],
        ['家', 'ie', 'house / home'],
        ['駅', 'eki', 'station'],
        ['店', 'mise', 'shop'],
        ['病院', 'byouin', 'hospital'],
        ['会社', 'kaisha', 'company'],
        ['国', 'kuni', 'country'],
        ['町', 'machi', 'town'],
        ['部屋', 'heya', 'room'],
        ['トイレ', 'toire', 'toilet'],
      ]),
      pack('n5-7', 'Stage 7 · Food', 'Meals and drinks you use every day.', [
        ['ご飯', 'gohan', 'meal / rice'],
        ['お茶', 'ocha', 'tea'],
        ['パン', 'pan', 'bread'],
        ['肉', 'niku', 'meat'],
        ['魚', 'sakana', 'fish'],
        ['野菜', 'yasai', 'vegetable'],
        ['果物', 'kudamono', 'fruit'],
        ['牛乳', 'gyuunyuu', 'milk'],
        ['卵', 'tamago', 'egg'],
        ['朝ごはん', 'asagohan', 'breakfast'],
      ]),
      pack('n5-8', 'Stage 8 · Everyday', 'Book, car, weather, question words.', [
        ['本', 'hon', 'book'],
        ['車', 'kuruma', 'car'],
        ['電話', 'denwa', 'telephone'],
        ['天気', 'tenki', 'weather'],
        ['雨', 'ame', 'rain'],
        ['名前', 'namae', 'name'],
        ['何', 'nani', 'what'],
        ['誰', 'dare', 'who'],
        ['どこ', 'doko', 'where'],
        ['どうして', 'doushite', 'why'],
      ]),
      pack('n5-9', 'Stage 9 · More verbs', 'Read, write, sleep, study, go home.', [
        ['読む', 'yomu', 'to read'],
        ['書く', 'kaku', 'to write'],
        ['寝る', 'neru', 'to sleep'],
        ['起きる', 'okiru', 'to wake up / get up'],
        ['働く', 'hataraku', 'to work'],
        ['勉強する', 'benkyou suru', 'to study'],
        ['帰る', 'kaeru', 'to go home / return'],
        ['入る', 'hairu', 'to enter'],
        ['出る', 'deru', 'to leave / exit'],
        ['使う', 'tsukau', 'to use'],
      ]),
      pack('n5-10', 'Stage 10 · Amount & extras', 'A little, a lot, already, very.', [
        ['一つ', 'hitotsu', 'one (thing)'],
        ['二つ', 'futatsu', 'two (things)'],
        ['少し', 'sukoshi', 'a little'],
        ['たくさん', 'takusan', 'a lot'],
        ['全部', 'zenbu', 'all'],
        ['もう', 'mou', 'already / more'],
        ['まだ', 'mada', 'not yet / still'],
        ['とても', 'totemo', 'very'],
        ['ちょっと', 'chotto', 'a bit'],
        ['大丈夫', 'daijoubu', 'all right / okay'],
      ]),
      mix('n5-mix', 'Stage 11 · N5 mixed review'),
    ],
  },
  n4: {
    id: 'n4',
    label: 'N4 words',
    kicker: 'Daily fluency',
    blurb: 'Popular JLPT N4 words: plans, travel, feelings, work, and useful verbs.',
    kind: 'vocab',
    group: 'words',
    stages: [
      pack(
        'n4-0',
        'Stage 0 · First N4',
        'Six high-frequency N4 words. Learn them, then tap A–F.',
        [
          ['予定', 'yotei', 'plan / schedule'],
          ['約束', 'yakusoku', 'promise'],
          ['準備', 'junbi', 'preparation'],
          ['必要', 'hitsuyou', 'necessary'],
          ['無理', 'muri', 'impossible / too much'],
          ['意味', 'imi', 'meaning'],
        ],
        { intro: true }
      ),
      pack('n4-1', 'Stage 1 · Think & decide', 'Know, forget, begin, choose.', [
        ['思う', 'omou', 'to think'],
        ['知る', 'shiru', 'to know'],
        ['分かる', 'wakaru', 'to understand'],
        ['教える', 'oshieru', 'to teach'],
        ['忘れる', 'wasureru', 'to forget'],
        ['始める', 'hajimeru', 'to begin'],
        ['終わる', 'owaru', 'to end'],
        ['続ける', 'tsuzukeru', 'to continue'],
        ['決める', 'kimeru', 'to decide'],
        ['選ぶ', 'erabu', 'to choose'],
      ]),
      pack('n4-2', 'Stage 2 · Plans & reasons', 'Experience, reason, situation.', [
        ['経験', 'keiken', 'experience'],
        ['理由', 'riyuu', 'reason'],
        ['場合', 'baai', 'case / situation'],
        ['説明', 'setsumei', 'explanation'],
        ['意見', 'iken', 'opinion'],
        ['質問', 'shitsumon', 'question'],
        ['答え', 'kotae', 'answer'],
        ['問題', 'mondai', 'problem / question'],
        ['簡単', 'kantan', 'simple / easy'],
        ['複雑', 'fukuzatsu', 'complicated'],
      ]),
      pack('n4-3', 'Stage 3 · Travel', 'Airport, ticket, reservation, luggage.', [
        ['旅行', 'ryokou', 'travel / trip'],
        ['空港', 'kuukou', 'airport'],
        ['地図', 'chizu', 'map'],
        ['切符', 'kippu', 'ticket'],
        ['予約', 'yoyaku', 'reservation'],
        ['荷物', 'nimotsu', 'luggage'],
        ['景色', 'keshiki', 'scenery'],
        ['建物', 'tatemono', 'building'],
        ['住所', 'juusho', 'address'],
        ['向こう', 'mukou', 'over there / beyond'],
      ]),
      pack('n4-4', 'Stage 4 · Feelings', 'Worry, kind, embarrassed, enough.', [
        ['気持ち', 'kimochi', 'feeling'],
        ['心配', 'shinpai', 'worry'],
        ['安心', 'anshin', 'relief'],
        ['残念', 'zannen', 'regrettable'],
        ['恥ずかしい', 'hazukashii', 'embarrassing'],
        ['優しい', 'yasashii', 'kind'],
        ['厳しい', 'kibishii', 'strict'],
        ['正しい', 'tadashii', 'correct'],
        ['足りる', 'tariru', 'to be enough'],
        ['壊れる', 'kowareru', 'to break'],
      ]),
      pack('n4-5', 'Stage 5 · Work & contact', 'Meeting, salary, reply, late.', [
        ['会議', 'kaigi', 'meeting'],
        ['給料', 'kyuuryou', 'salary'],
        ['返事', 'henji', 'reply'],
        ['連絡', 'renraku', 'contact'],
        ['届く', 'todoku', 'to arrive / be delivered'],
        ['遅れる', 'okureru', 'to be late'],
        ['間に合う', 'maniau', 'to be in time'],
        ['急ぐ', 'isogu', 'to hurry'],
        ['残る', 'nokoru', 'to remain'],
        ['会社員', 'kaishain', 'office worker'],
      ]),
      pack('n4-6', 'Stage 6 · Body & daily life', 'Health, clothes, housework.', [
        ['病気', 'byouki', 'illness'],
        ['元気', 'genki', 'healthy / energetic'],
        ['痛い', 'itai', 'painful'],
        ['疲れる', 'tsukareru', 'to get tired'],
        ['服', 'fuku', 'clothes'],
        ['洗う', 'arau', 'to wash'],
        ['片付ける', 'katazukeru', 'to tidy up'],
        ['捨てる', 'suteru', 'to throw away'],
        ['開く', 'aku / hiraku', 'to open'],
        ['閉じる', 'tojiru', 'to close'],
      ]),
      pack('n4-7', 'Stage 7 · More N4 verbs', 'Help, move, change, notice.', [
        ['助ける', 'tasukeru', 'to help / save'],
        ['手伝う', 'tetsudau', 'to help (assist)'],
        ['動く', 'ugoku', 'to move'],
        ['変わる', 'kawaru', 'to change'],
        ['気づく', 'kizuku', 'to notice'],
        ['見つける', 'mitsukeru', 'to find'],
        ['探す', 'sagasu', 'to search for'],
        ['届ける', 'todokeru', 'to deliver'],
        ['借りる', 'kariru', 'to borrow'],
        ['貸す', 'kasu', 'to lend'],
      ]),
      mix('n4-mix', 'Stage 8 · N4 mixed review'),
    ],
  },
  n3: {
    id: 'n3',
    label: 'N3 words',
    kicker: 'News & ideas',
    blurb: 'Popular JLPT N3 words: society, results, methods, and verbs of thinking.',
    kind: 'vocab',
    group: 'words',
    stages: [
      pack(
        'n3-0',
        'Stage 0 · First N3',
        'Six common N3 words from news and daily argument.',
        [
          ['関係', 'kankei', 'relation / connection'],
          ['社会', 'shakai', 'society'],
          ['実際', 'jissai', 'actually / in fact'],
          ['必要', 'hitsuyou', 'necessary'],
          ['情報', 'jouhou', 'information'],
          ['方法', 'houhou', 'method / way'],
        ],
        { intro: true }
      ),
      pack('n3-1', 'Stage 1 · Society', 'Economy, culture, environment, history.', [
        ['経済', 'keizai', 'economy'],
        ['政治', 'seiji', 'politics'],
        ['環境', 'kankyou', 'environment'],
        ['技術', 'gijutsu', 'technology / technique'],
        ['文化', 'bunka', 'culture'],
        ['歴史', 'rekishi', 'history'],
        ['教育', 'kyouiku', 'education'],
        ['国際', 'kokusai', 'international'],
        ['安全', 'anzen', 'safety'],
        ['平和', 'heiwa', 'peace'],
      ]),
      pack('n3-2', 'Stage 2 · Ideas', 'Cause, result, purpose, condition.', [
        ['機会', 'kikai', 'opportunity'],
        ['影響', 'eikyou', 'influence'],
        ['条件', 'jouken', 'condition'],
        ['結果', 'kekka', 'result'],
        ['原因', 'genin', 'cause'],
        ['目的', 'mokuteki', 'purpose'],
        ['内容', 'naiyou', 'contents'],
        ['状態', 'joutai', 'state / condition'],
        ['期間', 'kikan', 'period'],
        ['場合', 'baai', 'case / when'],
      ]),
      pack('n3-3', 'Stage 3 · Action nouns', 'Success, effort, change, report.', [
        ['参加', 'sanka', 'participation'],
        ['成功', 'seikou', 'success'],
        ['失敗', 'shippai', 'failure'],
        ['努力', 'doryoku', 'effort'],
        ['成長', 'seichou', 'growth'],
        ['変化', 'henka', 'change'],
        ['発展', 'hatten', 'development'],
        ['解決', 'kaiketsu', 'solution'],
        ['確認', 'kakunin', 'confirmation'],
        ['報告', 'houkoku', 'report'],
      ]),
      pack('n3-4', 'Stage 4 · Think verbs', 'Consider, investigate, compare.', [
        ['感じる', 'kanjiru', 'to feel'],
        ['考える', 'kangaeru', 'to consider / think'],
        ['調べる', 'shiraberu', 'to investigate / look up'],
        ['比べる', 'kuraberu', 'to compare'],
        ['信じる', 'shinjiru', 'to believe'],
        ['疑う', 'utagau', 'to doubt'],
        ['予想する', 'yosou suru', 'to predict'],
        ['判断する', 'handan suru', 'to judge'],
        ['説明する', 'setsumei suru', 'to explain'],
        ['紹介する', 'shoukai suru', 'to introduce'],
      ]),
      pack('n3-5', 'Stage 5 · Change verbs', 'Increase, decrease, protect, help.', [
        ['増える', 'fueru', 'to increase'],
        ['減る', 'heru', 'to decrease'],
        ['当たる', 'ataru', 'to hit / be right'],
        ['逃げる', 'nigeru', 'to run away'],
        ['守る', 'mamoru', 'to protect'],
        ['進む', 'susumu', 'to advance'],
        ['戻る', 'modoru', 'to return'],
        ['離れる', 'hanareru', 'to separate from'],
        ['集める', 'atsumeru', 'to gather'],
        ['伝える', 'tsutaeru', 'to convey'],
      ]),
      pack('n3-6', 'Stage 6 · Everyday N3', 'Convenient, serious, recently, limit.', [
        ['便利', 'benri', 'convenient'],
        ['不便', 'fuben', 'inconvenient'],
        ['真面目', 'majime', 'serious / earnest'],
        ['最近', 'saikin', 'recently'],
        ['将来', 'shourai', 'future'],
        ['普通', 'futsuu', 'normal / usual'],
        ['特に', 'toku ni', 'especially'],
        ['少なくとも', 'sukunaku tomo', 'at least'],
        ['限る', 'kagiru', 'to limit'],
        ['当然', 'touzen', 'natural / of course'],
      ]),
      pack('n3-7', 'Stage 7 · More N3', 'Responsibility, habit, detail, similar.', [
        ['責任', 'sekinin', 'responsibility'],
        ['習慣', 'shuukan', 'habit / custom'],
        ['詳細', 'shousai', 'details'],
        ['似ている', 'nite iru', 'to resemble'],
        ['例えば', 'tatoeba', 'for example'],
        ['つまり', 'tsumari', 'in other words'],
        ['しかし', 'shikashi', 'however'],
        ['そして', 'soshite', 'and then'],
        ['だから', 'dakara', 'so / therefore'],
        ['もし', 'moshi', 'if'],
      ]),
      mix('n3-mix', 'Stage 8 · N3 mixed review'),
    ],
  },
};
