/** Popular JLPT vocabulary in small teach-then-quiz stages. */

function pack(id, title, subtitle, items, extra = {}) {
  return {
    id,
    title,
    subtitle,
    teach: extra.teach || (items.length > 8 ? 'grid' : 'cards'),
    intro: Boolean(extra.intro),
    mix: Boolean(extra.mix),
    chars: items.map(([char, romaji, meaning]) => ({
      char,
      romaji,
      meaning,
      hint: '',
    })),
  };
}

function mix(id, title) {
  return pack(id, title, 'Everything in this level, shuffled.', [], { teach: 'grid', mix: true });
}

export const VOCAB_SCRIPTS = {
  n5: {
    id: 'n5',
    label: 'N5 words',
    kicker: 'First vocabulary',
    blurb: 'Popular JLPT N5 words for memorizing: greetings, body, school, travel, weather, and everyday verbs.',
    kind: 'vocab',
    group: 'words',
    stages: [
      pack(
        'n5-0',
        'Stage 0 · First words',
        'Six everyday words. See the writing, the sound, and the English meaning, then pick them from A–F.',
        [
          ['私', 'watashi', 'I / me'],
          ['日本', 'nihon', 'Japan'],
          ['人', 'hito', 'person'],
          ['水', 'mizu', 'water'],
          ['食べる', 'taberu', 'to eat'],
          ['行く', 'iku', 'to go'],
        ],
        { intro: true }
      ),
      pack('n5-1', 'Stage 1 · Greetings', 'Hello, thanks, yes, no, please.', [
        ['こんにちは', 'konnichiwa', 'hello'],
        ['おはよう', 'ohayou', 'good morning'],
        ['ありがとう', 'arigatou', 'thank you'],
        ['すみません', 'sumimasen', 'excuse me / sorry'],
        ['はい', 'hai', 'yes'],
        ['いいえ', 'iie', 'no'],
        ['お願いします', 'onegaishimasu', 'please'],
        ['さようなら', 'sayounara', 'goodbye'],
        ['はじめまして', 'hajimemashite', 'nice to meet you'],
        ['ください', 'kudasai', 'please give me'],
      ]),
      pack('n5-2', 'Stage 2 · People', 'Family, friends, school roles.', [
        ['あなた', 'anata', 'you'],
        ['彼', 'kare', 'he'],
        ['彼女', 'kanojo', 'she'],
        ['友達', 'tomodachi', 'friend'],
        ['先生', 'sensei', 'teacher'],
        ['学生', 'gakusei', 'student'],
        ['家族', 'kazoku', 'family'],
        ['母', 'haha', 'mother'],
        ['父', 'chichi', 'father'],
        ['子供', 'kodomo', 'child'],
      ]),
      pack('n5-3', 'Stage 3 · Time', 'Today, tomorrow, hours, every day.', [
        ['今日', 'kyou', 'today'],
        ['明日', 'ashita', 'tomorrow'],
        ['昨日', 'kinou', 'yesterday'],
        ['今', 'ima', 'now'],
        ['時', 'ji / toki', 'hour / time'],
        ['分', 'fun / pun', 'minute'],
        ['週', 'shuu', 'week'],
        ['年', 'nen / toshi', 'year'],
        ['毎日', 'mainichi', 'every day'],
        ['いつ', 'itsu', 'when'],
      ]),
      pack('n5-4', 'Stage 4 · Core verbs', 'Do, exist, come, see, buy.', [
        ['する', 'suru', 'to do'],
        ['ある', 'aru', 'to exist (thing)'],
        ['いる', 'iru', 'to exist (person)'],
        ['来る', 'kuru', 'to come'],
        ['見る', 'miru', 'to see / watch'],
        ['聞く', 'kiku', 'to hear / ask'],
        ['話す', 'hanasu', 'to speak'],
        ['飲む', 'nomu', 'to drink'],
        ['買う', 'kau', 'to buy'],
        ['待つ', 'matsu', 'to wait'],
      ]),
      pack('n5-5', 'Stage 5 · Adjectives', 'Big, small, hot, cheap, good.', [
        ['大きい', 'ookii', 'big'],
        ['小さい', 'chiisai', 'small'],
        ['新しい', 'atarashii', 'new'],
        ['古い', 'furui', 'old'],
        ['高い', 'takai', 'expensive / tall'],
        ['安い', 'yasui', 'cheap'],
        ['いい', 'ii', 'good'],
        ['悪い', 'warui', 'bad'],
        ['暑い', 'atsui', 'hot (weather)'],
        ['寒い', 'samui', 'cold (weather)'],
      ]),
      pack('n5-6', 'Stage 6 · Places', 'School, station, home, shop.', [
        ['学校', 'gakkou', 'school'],
        ['家', 'ie', 'house / home'],
        ['駅', 'eki', 'station'],
        ['店', 'mise', 'shop'],
        ['病院', 'byouin', 'hospital'],
        ['会社', 'kaisha', 'company'],
        ['国', 'kuni', 'country'],
        ['町', 'machi', 'town'],
        ['部屋', 'heya', 'room'],
        ['トイレ', 'toire', 'toilet'],
      ]),
      pack('n5-7', 'Stage 7 · Food', 'Meals and drinks you use every day.', [
        ['ご飯', 'gohan', 'meal / rice'],
        ['お茶', 'ocha', 'tea'],
        ['パン', 'pan', 'bread'],
        ['肉', 'niku', 'meat'],
        ['魚', 'sakana', 'fish'],
        ['野菜', 'yasai', 'vegetable'],
        ['果物', 'kudamono', 'fruit'],
        ['牛乳', 'gyuunyuu', 'milk'],
        ['卵', 'tamago', 'egg'],
        ['朝ごはん', 'asagohan', 'breakfast'],
      ]),
      pack('n5-8', 'Stage 8 · Everyday', 'Book, car, weather, question words.', [
        ['本', 'hon', 'book'],
        ['車', 'kuruma', 'car'],
        ['電話', 'denwa', 'telephone'],
        ['天気', 'tenki', 'weather'],
        ['雨', 'ame', 'rain'],
        ['名前', 'namae', 'name'],
        ['何', 'nani', 'what'],
        ['誰', 'dare', 'who'],
        ['どこ', 'doko', 'where'],
        ['どうして', 'doushite', 'why'],
      ]),
      pack('n5-9', 'Stage 9 · More verbs', 'Read, write, sleep, study, go home.', [
        ['読む', 'yomu', 'to read'],
        ['書く', 'kaku', 'to write'],
        ['寝る', 'neru', 'to sleep'],
        ['起きる', 'okiru', 'to wake up / get up'],
        ['働く', 'hataraku', 'to work'],
        ['勉強する', 'benkyou suru', 'to study'],
        ['帰る', 'kaeru', 'to go home / return'],
        ['入る', 'hairu', 'to enter'],
        ['出る', 'deru', 'to leave / exit'],
        ['使う', 'tsukau', 'to use'],
      ]),
      pack('n5-10', 'Stage 10 · Amount & extras', 'A little, a lot, already, very.', [
        ['一つ', 'hitotsu', 'one (thing)'],
        ['二つ', 'futatsu', 'two (things)'],
        ['少し', 'sukoshi', 'a little'],
        ['たくさん', 'takusan', 'a lot'],
        ['全部', 'zenbu', 'all'],
        ['もう', 'mou', 'already / more'],
        ['まだ', 'mada', 'not yet / still'],
        ['とても', 'totemo', 'very'],
        ['ちょっと', 'chotto', 'a bit'],
        ['大丈夫', 'daijoubu', 'all right / okay'],
      ]),
      mix('n5-mix', 'Stage 11 · N5 review A'),
      pack('n5-11', 'Stage 12 · Body', 'Head, hands, voice — point to yourself.', [
        ['頭', 'atama', 'head'],
        ['顔', 'kao', 'face'],
        ['髪', 'kami', 'hair'],
        ['目', 'me', 'eye'],
        ['耳', 'mimi', 'ear'],
        ['口', 'kuchi', 'mouth'],
        ['手', 'te', 'hand'],
        ['足', 'ashi', 'foot / leg'],
        ['体', 'karada', 'body'],
        ['声', 'koe', 'voice'],
      ]),
      pack('n5-12', 'Stage 13 · Clothes & color', 'What you wear and basic colors.', [
        ['服', 'fuku', 'clothes'],
        ['靴', 'kutsu', 'shoes'],
        ['帽子', 'boushi', 'hat'],
        ['傘', 'kasa', 'umbrella'],
        ['着る', 'kiru', 'to wear (clothes)'],
        ['色', 'iro', 'color'],
        ['赤い', 'akai', 'red'],
        ['青い', 'aoi', 'blue'],
        ['白い', 'shiroi', 'white'],
        ['黒い', 'kuroi', 'black'],
      ]),
      pack('n5-13', 'Stage 14 · Getting around', 'Trains, buses, walk, get on, get off.', [
        ['電車', 'densha', 'train'],
        ['バス', 'basu', 'bus'],
        ['飛行機', 'hikouki', 'airplane'],
        ['自転車', 'jitensha', 'bicycle'],
        ['歩く', 'aruku', 'to walk'],
        ['乗る', 'noru', 'to ride / get on'],
        ['降りる', 'oriru', 'to get off'],
        ['道', 'michi', 'road / way'],
        ['右', 'migi', 'right'],
        ['左', 'hidari', 'left'],
      ]),
      pack('n5-14', 'Stage 15 · Weather & seasons', 'Sun, rain, snow, spring to winter.', [
        ['晴れ', 'hare', 'clear weather'],
        ['曇り', 'kumori', 'cloudy'],
        ['雪', 'yuki', 'snow'],
        ['風', 'kaze', 'wind'],
        ['空', 'sora', 'sky'],
        ['春', 'haru', 'spring'],
        ['夏', 'natsu', 'summer'],
        ['秋', 'aki', 'autumn'],
        ['冬', 'fuyu', 'winter'],
        ['熱い', 'atsui', 'hot (to the touch)'],
      ]),
      pack('n5-15', 'Stage 16 · More adjectives', 'Long, fast, near, difficult.', [
        ['長い', 'nagai', 'long'],
        ['短い', 'mijikai', 'short'],
        ['速い', 'hayai', 'fast'],
        ['遅い', 'osoi', 'slow / late'],
        ['多い', 'ooi', 'many'],
        ['少ない', 'sukunai', 'few'],
        ['近い', 'chikai', 'near'],
        ['遠い', 'tooi', 'far'],
        ['難しい', 'muzukashii', 'difficult'],
        ['易しい', 'yasashii', 'easy'],
      ]),
      pack('n5-16', 'Stage 17 · More verbs', 'Run, sit, open, hold, swim.', [
        ['走る', 'hashiru', 'to run'],
        ['座る', 'suwaru', 'to sit'],
        ['立つ', 'tatsu', 'to stand'],
        ['開ける', 'akeru', 'to open'],
        ['閉める', 'shimeru', 'to close'],
        ['持つ', 'motsu', 'to hold / have'],
        ['置く', 'oku', 'to put / place'],
        ['泳ぐ', 'oyogu', 'to swim'],
        ['歌う', 'utau', 'to sing'],
        ['死ぬ', 'shinu', 'to die'],
      ]),
      pack('n5-17', 'Stage 18 · Family extra', 'Siblings, grandparents, husband, wife.', [
        ['兄', 'ani', 'older brother'],
        ['姉', 'ane', 'older sister'],
        ['弟', 'otouto', 'younger brother'],
        ['妹', 'imouto', 'younger sister'],
        ['祖父', 'sofu', 'grandfather'],
        ['祖母', 'sobo', 'grandmother'],
        ['両親', 'ryoushin', 'parents'],
        ['夫', 'otto', 'husband'],
        ['妻', 'tsuma', 'wife'],
        ['赤ちゃん', 'akachan', 'baby'],
      ]),
      pack('n5-18', 'Stage 19 · School things', 'Class, homework, test, pencil, university.', [
        ['授業', 'jugyou', 'class / lesson'],
        ['宿題', 'shukudai', 'homework'],
        ['試験', 'shiken', 'exam'],
        ['辞書', 'jisho', 'dictionary'],
        ['鉛筆', 'enpitsu', 'pencil'],
        ['紙', 'kami', 'paper'],
        ['机', 'tsukue', 'desk'],
        ['大学', 'daigaku', 'university'],
        ['教室', 'kyoushitsu', 'classroom'],
        ['時計', 'tokei', 'clock / watch'],
      ]),
      mix('n5-mix2', 'Stage 20 · N5 mixed review'),
    ],
  },
  n4: {
    id: 'n4',
    label: 'N4 words',
    kicker: 'Daily fluency',
    blurb: 'Popular JLPT N4 words for memorizing: plans, travel, shopping, feelings, and extra verbs.',
    kind: 'vocab',
    group: 'words',
    stages: [
      pack(
        'n4-0',
        'Stage 0 · First N4',
        'Six high-frequency N4 words. Learn them, then tap A–F.',
        [
          ['予定', 'yotei', 'plan / schedule'],
          ['約束', 'yakusoku', 'promise'],
          ['準備', 'junbi', 'preparation'],
          ['必要', 'hitsuyou', 'necessary'],
          ['無理', 'muri', 'impossible / too much'],
          ['意味', 'imi', 'meaning'],
        ],
        { intro: true }
      ),
      pack('n4-1', 'Stage 1 · Think & decide', 'Know, forget, begin, choose.', [
        ['思う', 'omou', 'to think'],
        ['知る', 'shiru', 'to know'],
        ['分かる', 'wakaru', 'to understand'],
        ['教える', 'oshieru', 'to teach'],
        ['忘れる', 'wasureru', 'to forget'],
        ['始める', 'hajimeru', 'to begin'],
        ['終わる', 'owaru', 'to end'],
        ['続ける', 'tsuzukeru', 'to continue'],
        ['決める', 'kimeru', 'to decide'],
        ['選ぶ', 'erabu', 'to choose'],
      ]),
      pack('n4-2', 'Stage 2 · Plans & reasons', 'Experience, reason, situation.', [
        ['経験', 'keiken', 'experience'],
        ['理由', 'riyuu', 'reason'],
        ['場合', 'baai', 'case / situation'],
        ['説明', 'setsumei', 'explanation'],
        ['意見', 'iken', 'opinion'],
        ['質問', 'shitsumon', 'question'],
        ['答え', 'kotae', 'answer'],
        ['問題', 'mondai', 'problem / question'],
        ['簡単', 'kantan', 'simple / easy'],
        ['複雑', 'fukuzatsu', 'complicated'],
      ]),
      pack('n4-3', 'Stage 3 · Travel', 'Airport, ticket, reservation, luggage.', [
        ['旅行', 'ryokou', 'travel / trip'],
        ['空港', 'kuukou', 'airport'],
        ['地図', 'chizu', 'map'],
        ['切符', 'kippu', 'ticket'],
        ['予約', 'yoyaku', 'reservation'],
        ['荷物', 'nimotsu', 'luggage'],
        ['景色', 'keshiki', 'scenery'],
        ['建物', 'tatemono', 'building'],
        ['住所', 'juusho', 'address'],
        ['向こう', 'mukou', 'over there / beyond'],
      ]),
      pack('n4-4', 'Stage 4 · Feelings', 'Worry, kind, embarrassed, enough.', [
        ['気持ち', 'kimochi', 'feeling'],
        ['心配', 'shinpai', 'worry'],
        ['安心', 'anshin', 'relief'],
        ['残念', 'zannen', 'regrettable'],
        ['恥ずかしい', 'hazukashii', 'embarrassing'],
        ['優しい', 'yasashii', 'kind'],
        ['厳しい', 'kibishii', 'strict'],
        ['正しい', 'tadashii', 'correct'],
        ['足りる', 'tariru', 'to be enough'],
        ['壊れる', 'kowareru', 'to break'],
      ]),
      pack('n4-5', 'Stage 5 · Work & contact', 'Meeting, salary, reply, late.', [
        ['会議', 'kaigi', 'meeting'],
        ['給料', 'kyuuryou', 'salary'],
        ['返事', 'henji', 'reply'],
        ['連絡', 'renraku', 'contact'],
        ['届く', 'todoku', 'to arrive / be delivered'],
        ['遅れる', 'okureru', 'to be late'],
        ['間に合う', 'maniau', 'to be in time'],
        ['急ぐ', 'isogu', 'to hurry'],
        ['残る', 'nokoru', 'to remain'],
        ['会社員', 'kaishain', 'office worker'],
      ]),
      pack('n4-6', 'Stage 6 · Body & daily life', 'Health, clothes, housework.', [
        ['病気', 'byouki', 'illness'],
        ['元気', 'genki', 'healthy / energetic'],
        ['痛い', 'itai', 'painful'],
        ['疲れる', 'tsukareru', 'to get tired'],
        ['服', 'fuku', 'clothes'],
        ['洗う', 'arau', 'to wash'],
        ['片付ける', 'katazukeru', 'to tidy up'],
        ['捨てる', 'suteru', 'to throw away'],
        ['開く', 'aku / hiraku', 'to open'],
        ['閉じる', 'tojiru', 'to close'],
      ]),
      pack('n4-7', 'Stage 7 · More N4 verbs', 'Help, move, change, notice.', [
        ['助ける', 'tasukeru', 'to help / save'],
        ['手伝う', 'tetsudau', 'to help (assist)'],
        ['動く', 'ugoku', 'to move'],
        ['変わる', 'kawaru', 'to change'],
        ['気づく', 'kizuku', 'to notice'],
        ['見つける', 'mitsukeru', 'to find'],
        ['探す', 'sagasu', 'to search for'],
        ['届ける', 'todokeru', 'to deliver'],
        ['借りる', 'kariru', 'to borrow'],
        ['貸す', 'kasu', 'to lend'],
      ]),
      mix('n4-mix', 'Stage 8 · N4 review A'),
      pack('n4-8', 'Stage 9 · Nature', 'Sea, forest, star, island, stone.', [
        ['海', 'umi', 'sea'],
        ['川', 'kawa', 'river'],
        ['森', 'mori', 'forest'],
        ['島', 'shima', 'island'],
        ['湖', 'mizuumi', 'lake'],
        ['星', 'hoshi', 'star'],
        ['雲', 'kumo', 'cloud'],
        ['石', 'ishi', 'stone'],
        ['池', 'ike', 'pond'],
        ['光', 'hikari', 'light'],
      ]),
      pack('n4-9', 'Stage 10 · Shopping', 'Price, pay, wallet, order, customer.', [
        ['値段', 'nedan', 'price'],
        ['払う', 'harau', 'to pay'],
        ['売る', 'uru', 'to sell'],
        ['財布', 'saifu', 'wallet'],
        ['現金', 'genkin', 'cash'],
        ['袋', 'fukuro', 'bag'],
        ['注文', 'chuumon', 'order'],
        ['客', 'kyaku', 'customer'],
        ['お釣り', 'otsuri', 'change (money)'],
        ['割引', 'waribiki', 'discount'],
      ]),
      pack('n4-10', 'Stage 11 · Shape & taste', 'Wide, heavy, sweet, spicy.', [
        ['広い', 'hiroi', 'wide / spacious'],
        ['狭い', 'semai', 'narrow'],
        ['重い', 'omoi', 'heavy'],
        ['軽い', 'karui', 'light (weight)'],
        ['厚い', 'atsui', 'thick'],
        ['薄い', 'usui', 'thin'],
        ['深い', 'fukai', 'deep'],
        ['甘い', 'amai', 'sweet'],
        ['辛い', 'karai', 'spicy / salty'],
        ['苦い', 'nigai', 'bitter'],
      ]),
      pack('n4-11', 'Stage 12 · More N4 verbs', 'Laugh, cry, fix, cook, pick up.', [
        ['笑う', 'warau', 'to laugh'],
        ['泣く', 'naku', 'to cry'],
        ['怒る', 'okoru', 'to get angry'],
        ['直す', 'naosu', 'to fix'],
        ['壊す', 'kowasu', 'to break (something)'],
        ['並べる', 'naraberu', 'to line up / arrange'],
        ['折る', 'oru', 'to fold / break (a bone)'],
        ['焼く', 'yaku', 'to bake / grill'],
        ['落とす', 'otosu', 'to drop'],
        ['拾う', 'hirou', 'to pick up'],
      ]),
      pack('n4-12', 'Stage 13 · Life events', 'Marriage, graduation, birthday, gift.', [
        ['結婚', 'kekkon', 'marriage'],
        ['卒業', 'sotsugyou', 'graduation'],
        ['入学', 'nyuugaku', 'entering school'],
        ['面接', 'mensetsu', 'interview'],
        ['誕生日', 'tanjoubi', 'birthday'],
        ['プレゼント', 'purezento', 'present'],
        ['お祝い', 'oiwai', 'celebration'],
        ['夢', 'yume', 'dream'],
        ['得意', 'tokui', 'one’s strong point'],
        ['苦手', 'nigate', 'one’s weak point'],
      ]),
      pack('n4-13', 'Stage 14 · Inner life', 'Hope, confidence, courage, character.', [
        ['希望', 'kibou', 'hope'],
        ['自信', 'jishin', 'confidence'],
        ['勇気', 'yuuki', 'courage'],
        ['性格', 'seikaku', 'personality'],
        ['記憶', 'kioku', 'memory'],
        ['想像', 'souzou', 'imagination'],
        ['遠慮', 'enryo', 'restraint / holding back'],
        ['謝る', 'ayamaru', 'to apologize'],
        ['褒める', 'homeru', 'to praise'],
        ['叱る', 'shikaru', 'to scold'],
      ]),
      mix('n4-mix2', 'Stage 15 · N4 mixed review'),
    ],
  },
  n3: {
    id: 'n3',
    label: 'N3 words',
    kicker: 'News & ideas',
    blurb: 'Popular JLPT N3 words for memorizing: society, work, feelings, and abstract nouns.',
    kind: 'vocab',
    group: 'words',
    stages: [
      pack(
        'n3-0',
        'Stage 0 · First N3',
        'Six common N3 words from news and daily argument.',
        [
          ['関係', 'kankei', 'relation / connection'],
          ['社会', 'shakai', 'society'],
          ['実際', 'jissai', 'actually / in fact'],
          ['必要', 'hitsuyou', 'necessary'],
          ['情報', 'jouhou', 'information'],
          ['方法', 'houhou', 'method / way'],
        ],
        { intro: true }
      ),
      pack('n3-1', 'Stage 1 · Society', 'Economy, culture, environment, history.', [
        ['経済', 'keizai', 'economy'],
        ['政治', 'seiji', 'politics'],
        ['環境', 'kankyou', 'environment'],
        ['技術', 'gijutsu', 'technology / technique'],
        ['文化', 'bunka', 'culture'],
        ['歴史', 'rekishi', 'history'],
        ['教育', 'kyouiku', 'education'],
        ['国際', 'kokusai', 'international'],
        ['安全', 'anzen', 'safety'],
        ['平和', 'heiwa', 'peace'],
      ]),
      pack('n3-2', 'Stage 2 · Ideas', 'Cause, result, purpose, condition.', [
        ['機会', 'kikai', 'opportunity'],
        ['影響', 'eikyou', 'influence'],
        ['条件', 'jouken', 'condition'],
        ['結果', 'kekka', 'result'],
        ['原因', 'genin', 'cause'],
        ['目的', 'mokuteki', 'purpose'],
        ['内容', 'naiyou', 'contents'],
        ['状態', 'joutai', 'state / condition'],
        ['期間', 'kikan', 'period'],
        ['場合', 'baai', 'case / when'],
      ]),
      pack('n3-3', 'Stage 3 · Action nouns', 'Success, effort, change, report.', [
        ['参加', 'sanka', 'participation'],
        ['成功', 'seikou', 'success'],
        ['失敗', 'shippai', 'failure'],
        ['努力', 'doryoku', 'effort'],
        ['成長', 'seichou', 'growth'],
        ['変化', 'henka', 'change'],
        ['発展', 'hatten', 'development'],
        ['解決', 'kaiketsu', 'solution'],
        ['確認', 'kakunin', 'confirmation'],
        ['報告', 'houkoku', 'report'],
      ]),
      pack('n3-4', 'Stage 4 · Think verbs', 'Consider, investigate, compare.', [
        ['感じる', 'kanjiru', 'to feel'],
        ['考える', 'kangaeru', 'to consider / think'],
        ['調べる', 'shiraberu', 'to investigate / look up'],
        ['比べる', 'kuraberu', 'to compare'],
        ['信じる', 'shinjiru', 'to believe'],
        ['疑う', 'utagau', 'to doubt'],
        ['予想する', 'yosou suru', 'to predict'],
        ['判断する', 'handan suru', 'to judge'],
        ['説明する', 'setsumei suru', 'to explain'],
        ['紹介する', 'shoukai suru', 'to introduce'],
      ]),
      pack('n3-5', 'Stage 5 · Change verbs', 'Increase, decrease, protect, help.', [
        ['増える', 'fueru', 'to increase'],
        ['減る', 'heru', 'to decrease'],
        ['当たる', 'ataru', 'to hit / be right'],
        ['逃げる', 'nigeru', 'to run away'],
        ['守る', 'mamoru', 'to protect'],
        ['進む', 'susumu', 'to advance'],
        ['戻る', 'modoru', 'to return'],
        ['離れる', 'hanareru', 'to separate from'],
        ['集める', 'atsumeru', 'to gather'],
        ['伝える', 'tsutaeru', 'to convey'],
      ]),
      pack('n3-6', 'Stage 6 · Everyday N3', 'Convenient, serious, recently, limit.', [
        ['便利', 'benri', 'convenient'],
        ['不便', 'fuben', 'inconvenient'],
        ['真面目', 'majime', 'serious / earnest'],
        ['最近', 'saikin', 'recently'],
        ['将来', 'shourai', 'future'],
        ['普通', 'futsuu', 'normal / usual'],
        ['特に', 'toku ni', 'especially'],
        ['少なくとも', 'sukunaku tomo', 'at least'],
        ['限る', 'kagiru', 'to limit'],
        ['当然', 'touzen', 'natural / of course'],
      ]),
      pack('n3-7', 'Stage 7 · More N3', 'Responsibility, habit, detail, similar.', [
        ['責任', 'sekinin', 'responsibility'],
        ['習慣', 'shuukan', 'habit / custom'],
        ['詳細', 'shousai', 'details'],
        ['似ている', 'nite iru', 'to resemble'],
        ['例えば', 'tatoeba', 'for example'],
        ['つまり', 'tsumari', 'in other words'],
        ['しかし', 'shikashi', 'however'],
        ['そして', 'soshite', 'and then'],
        ['だから', 'dakara', 'so / therefore'],
        ['もし', 'moshi', 'if'],
      ]),
      mix('n3-mix', 'Stage 8 · N3 review A'),
      pack('n3-8', 'Stage 9 · Work & money', 'Job, contract, profit, customer, product.', [
        ['職業', 'shokugyou', 'occupation'],
        ['就職', 'shuushoku', 'finding employment'],
        ['契約', 'keiyaku', 'contract'],
        ['利益', 'rieki', 'profit'],
        ['損失', 'sonshitsu', 'loss'],
        ['顧客', 'kokyaku', 'client / customer'],
        ['商品', 'shouhin', 'product / goods'],
        ['在庫', 'zaiko', 'stock / inventory'],
        ['給料', 'kyuuryou', 'salary'],
        ['税金', 'zeikin', 'tax'],
      ]),
      pack('n3-9', 'Stage 10 · Feelings', 'Moved, anxious, grateful, tense, regret.', [
        ['感動', 'kandou', 'being moved (emotionally)'],
        ['不安', 'fuan', 'anxiety'],
        ['満足', 'manzoku', 'satisfaction'],
        ['緊張', 'kinchou', 'nervousness'],
        ['感謝', 'kansha', 'gratitude'],
        ['尊敬', 'sonkei', 'respect'],
        ['後悔', 'koukai', 'regret'],
        ['期待', 'kitai', 'expectation'],
        ['失望', 'shitsubou', 'disappointment'],
        ['興奮', 'koufun', 'excitement'],
      ]),
      pack('n3-10', 'Stage 11 · Ideas extra', 'Reality, value, duty, freedom, truth.', [
        ['現実', 'genjitsu', 'reality'],
        ['理想', 'risou', 'ideal'],
        ['価値', 'kachi', 'value'],
        ['義務', 'gimu', 'duty / obligation'],
        ['自由', 'jiyuu', 'freedom'],
        ['平等', 'byoudou', 'equality'],
        ['正義', 'seigi', 'justice'],
        ['真実', 'shinjitsu', 'truth'],
        ['秘密', 'himitsu', 'secret'],
        ['権利', 'kenri', 'right (legal)'],
      ]),
      pack('n3-11', 'Stage 12 · Action verbs', 'Achieve, improve, use, agree, belong.', [
        ['達成する', 'tassei suru', 'to achieve'],
        ['評価する', 'hyouka suru', 'to evaluate'],
        ['改善する', 'kaizen suru', 'to improve'],
        ['維持する', 'iji suru', 'to maintain'],
        ['提供する', 'teikyou suru', 'to provide'],
        ['利用する', 'riyou suru', 'to use / make use of'],
        ['所属する', 'shozoku suru', 'to belong to'],
        ['賛成する', 'sansei suru', 'to agree / approve'],
        ['反対する', 'hantai suru', 'to oppose'],
        ['適用する', 'tekiyou suru', 'to apply (a rule)'],
      ]),
      pack('n3-12', 'Stage 13 · How often / how much', 'Suddenly, always, almost, each.', [
        ['突然', 'totsuzen', 'suddenly'],
        ['ついに', 'tsui ni', 'finally / at last'],
        ['必ず', 'kanarazu', 'without fail / always'],
        ['絶対', 'zettai', 'absolutely'],
        ['かなり', 'kanari', 'considerably'],
        ['ずいぶん', 'zuibun', 'quite / fairly'],
        ['ますます', 'masumasu', 'more and more'],
        ['ほとんど', 'hotondo', 'almost / most'],
        ['各', 'kaku', 'each / every'],
        ['全体', 'zentai', 'the whole'],
      ]),
      pack('n3-13', 'Stage 14 · More N3 verbs', 'Prevent, occur, include, avoid.', [
        ['防ぐ', 'fusegu', 'to prevent'],
        ['起こる', 'okoru', 'to occur'],
        ['含む', 'fukumu', 'to include'],
        ['避ける', 'sakeru', 'to avoid'],
        ['示す', 'shimesu', 'to indicate / show'],
        ['述べる', 'noberu', 'to state'],
        ['求める', 'motomeru', 'to seek / request'],
        ['認める', 'mitomeru', 'to admit / recognize'],
        ['現れる', 'arawareru', 'to appear'],
        ['思い出す', 'omoidasu', 'to remember / recall'],
      ]),
      mix('n3-mix2', 'Stage 15 · N3 mixed review'),
    ],
  },
};
